language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: GIKVivsTITpn4F3psoSfsifTdyTvFpMdcIARybdUhw8GcDof3Z+25ssqu46vSIIA+hG8GPBoC9Nx6ZQRzS93sbWUKjMbxXvAACd1NL6S1LGSsEiumDzPizhnVaUTdLUcPljwuD0dGvlNeax7aXJPRXLVDixvvgcjvfnzlXo1DA0=
