language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: Psctb3qUs3iAze4g9RbRts5tcFclGie2PZXu7GpNdY8OfKYbPqrJabvkoDhUGgjwni/hIn7OSZDC8C6EpRBRw1X2k3m5vRIdl3+ptCqXomYewkJui025CDZoudqlQVg/QDEOLooN8d7WgxvFGVFFtE86hw30gS/2cGCqCgLCr5k=