language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: "GIKVivsTITpn4F3psoSfsifTdyTvFpMdcIARybdUhw8GcDof3Z+25ssqu46vSIIA+hG8GPBoC9Nx6ZQRzS93sbWUKjMbxXvAACd1NL6S1LGSsEiumDzPizhnVaUTdLUcPljwuD0dGvlNeax7aXJPRXLVDixvvgcjvfnzlXo1DA0="
        - secure: "Hng5EilRSl0qE+jyQhCzzVzrFCChAElvznkXXpAEayAd8oF0mQcebtWrrcnf/PLVcZ2IdAqBTuLb0X2VdVkCwvIO+f+SNB25rx13JNX0EL63wFt3+3BhPVT5lIJUYWwePuXyWz3Q6MbHjFYkYw9v/O+zg9jnslFvV5qRGJKD5oQ="
        - secure: "RtlrDkFv1YvdYWRR2xhzMAGgtlVNcX/WPgvvpdblzcxKUp/yVZOVyBlVY2sVb70nD4j0a/4HbtsPk/aNo/GzIuIC9OS+2FR/5BDOMWyT+7WTm6GD+oEAwT7hATs/slrY0ja7CuoUKbtUqYeFCE5ph1Ozcy+WujfOZkRX7MtI3zE="
