language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: PREbaHvbBkZok4bkMwCR3VZ5ZvdRCuxqBMvkFiVoAtKDKnMeOpTjvZ1XFulVKI/VzJgeBzdFzdcvVWd+GYMQxwarOUx96kR73dc+C+R40uyT6ly2RLcQvlP4/FzZZkDOTLhnyHiqZ+dJ8jac3rETew1u4/UDaKyKR+tILgd0qyw=
        - secure: VGdai28MAktO20glP4HYJaVfnyD0MaoXU0Al6wm0el20sC3VCmrAcy0J0z69lhylKowZ3hnxCKgcLXgsfyl7PM9Lvc9/o2Q+v0R6fN5Us7psdXLXT/2CtVssRRrqKznJfOgEHnccy4Du6GWBudJBpr6MbkmV3yBGGH/7WL4lzJQ=