language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: MJZlRz8m6Y10y8mkhKHmpxoFnhOaELMMSTCFCjYlnLfBEWeoZR8b/dBj6nTJoJSnlCefvl6cST9KrR48m0ngnq/7uLRTlRjH8SZvC3nURXWfXfhrdWD8pnTJugkfvZGiPvRnvmZYL5rVRjjkeZ1c1/78fdkNEFO8r87e9CEizN0=