language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: UpBO2DECanVVx33woml9oB/8r2kEpoRzTxHfqiACafpsS3kaxHBKCd1A5a5LgKkb54hJqp0kZfTQwCD7yRr/eJRzQ0OIL1/mqdLuS+fV8A8NuASFcOTMlggbw9jpNe1Kcwn+Bct/mOmVMVwxTuu6uBh9rcY6FKZVIywY/Jsg+8Q=