language: node_js

node_js : 
    - "0.10"
    - "0.11"

env:
    global:
        - secure: PREbaHvbBkZok4bkMwCR3VZ5ZvdRCuxqBMvkFiVoAtKDKnMeOpTjvZ1XFulVKI/VzJgeBzdFzdcvVWd+GYMQxwarOUx96kR73dc+C+R40uyT6ly2RLcQvlP4/FzZZkDOTLhnyHiqZ+dJ8jac3rETew1u4/UDaKyKR+tILgd0qyw=
        - secure: QBaipSFhlCJ+KoJSzYZnz4y8rj3ttCGnePCsul2JpqlcmEY15b5FdQ96W5C9nFd9jPmseo6C/y5XN23LvRw4FCAi5Q8NleM8ExQoR/+nYBKnTaKCZ5CWjC8Pv4wA5W8uCVWrz7FPE3LSkLjWULWowNLECL0GaVWUXHoUisHDG58=